version: '3.9'

services:
  # mongoDB services
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
      
# elasticsearch services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch_container
    restart: always
    ports:
      - ${ELASTIC_PORT}:${ELASTIC_PORT}
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

networks:
  forecast_network:
    driver: bridge