version: '3.9'

services:
  # mongoDB services
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    restart: always
    ports:
      - 27017:27017
      
# elasticsearch services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch_container
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

# python api services
  python_api:
    build: .
    container_name: python_container
    restart: always
    ports:
      - 5000:5000
    links:
      - mongo
      - elasticsearch

networks:
  forecast_network:
    driver: bridge